name: Pull request checks

on:
  push:
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
    check_tests:
      name: Run tests
      runs-on: ubuntu-22.04
      steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run pytest
        run: make test
